development:
  secret_key_base: 97b02dd254271f4b259379ba6b468890c93291f0604e2b4c1639d9e5615f591c23fbb151c5d35510503ae3727878900577d80f4b37f0951a149cfad4fe2ac774

test:
  secret_key_base: 35d62789c7479e6b4fa427245370072f9ecb4f91d18df7809f14e7b657fc6b1c2583c81b648bee0027f084073382d3cf70e82eaefdcaab97a6071acf8511b982

production:
  secret_key_base: <%= PRIVATE["secret_key_base"] %>
